services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: api
    ports:
      - '4000:4000' # Maps host port 4000 to container port 4000
    volumes:
      - .:/app # Syncs your local code with the container
      - /app/node_modules # Prevents overwriting node_modules
    environment:
      DATABASE_URL: 'postgresql://postgres:postgres@db:5432/vibe-db'
    command: pnpm run start:dev # Use development-specific command
    depends_on:
      - db
  db:
    image: postgres:15
    container_name: postgres_db
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: vibe-db
    volumes:
      - postgres_data:/var/lib/postgresql/data # Persist database data

volumes:
  postgres_data:
